- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
  - name: Copy WAR file to Tomcat
    copy:
     src: "/var/snap/jenkins/4865/workspace/myansiblewebapp/target/MavenAnsibleWebApp1.war"
     dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
     remote_src: no
  - name: Restart Tomcat manually on Ubuntu
    become: true
    shell: |
    /opt/tomcat/bin/shutdown.sh || true
    sleep 5
    /opt/tomcat/bin/startup.sh
